# Generated by Django 5.2.12 on 2026-04-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(help_text='Formato: GVC-XXXX', max_length=20, unique=True, verbose_name='ID de Atleta')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='athletes/', verbose_name='Foto')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergencia')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Emergencia')),
                ('status', models.CharField(choices=[('inscrito', 'Inscrito'), ('periodo_prueba', 'Período de Prueba'), ('suspendido', 'Suspendido'), ('retirado', 'Retirado')], default='inscrito', max_length=20, verbose_name='Estado')),
                ('date_joined', models.DateField(verbose_name='Fecha de Ingreso')),
                ('performance', models.IntegerField(default=0, help_text='Porcentaje de rendimiento (0-100)', verbose_name='Rendimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('level', models.CharField(choices=[('academia', 'Academia'), ('novato', 'Novato'), ('competicion', 'Competición'), ('elite', 'Élite')], default='academia', max_length=20, verbose_name='Nivel')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
    ]
