# Generated by Django 5.2.12 on 2026-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='jersey_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de camiseta (1-99)', null=True, verbose_name='Dorsal'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id',
            field=models.CharField(blank=True, help_text='Generado automáticamente: GVC-XXXX', max_length=20, unique=True, verbose_name='ID de Atleta'),
        ),
    ]
