# Generated by Django 5.2.12 on 2026-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_athlete_jersey_number_alter_athlete_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='gender',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=15, verbose_name='Género'),
        ),
    ]
