# Generated by Django 5.2.12 on 2026-04-02 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='coach',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'entrenador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='schedules.court', verbose_name='Cancha'),
        ),
    ]
