# Generated by Django 5.2.12 on 2026-04-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('competition_type', models.CharField(choices=[('liga', 'Liga'), ('torneo', 'Torneo'), ('amistoso', 'Amistoso'), ('invitacional', 'Invitacional')], default='torneo', max_length=20, verbose_name='Tipo')),
                ('phase', models.CharField(choices=[('fase_grupos', 'Fase de Grupos'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('regular', 'Temporada Regular')], default='regular', max_length=20, verbose_name='Fase')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Sede')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Evento Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competición',
                'verbose_name_plural': 'Competiciones',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='Equipo Local')),
                ('away_team', models.CharField(max_length=100, verbose_name='Equipo Visitante')),
                ('match_date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Sede')),
                ('home_score', models.IntegerField(default=0, verbose_name='Sets Local')),
                ('away_score', models.IntegerField(default=0, verbose_name='Sets Visitante')),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('result', models.CharField(choices=[('ganado', 'Ganado'), ('perdido', 'Perdido'), ('empate', 'Empate'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20, verbose_name='Resultado')),
                ('phase', models.CharField(blank=True, choices=[('fase_grupos', 'Fase de Grupos'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('final', 'Final'), ('regular', 'Temporada Regular')], max_length=20, verbose_name='Fase')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.competition', verbose_name='Competición')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Equipo')),
                ('position', models.IntegerField(verbose_name='Posición')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos')),
                ('matches_played', models.IntegerField(default=0, verbose_name='PJ')),
                ('wins', models.IntegerField(default=0, verbose_name='PG')),
                ('losses', models.IntegerField(default=0, verbose_name='PP')),
                ('sets_won', models.IntegerField(default=0, verbose_name='SG')),
                ('sets_lost', models.IntegerField(default=0, verbose_name='SP')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='competitions.competition', verbose_name='Competición')),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Tabla de Posiciones',
                'ordering': ['competition', 'position'],
                'unique_together': {('competition', 'team_name')},
            },
        ),
    ]
