# Generated by Django 5.2.12 on 2026-04-04 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_gender'),
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Asistente'),
        ),
        migrations.AddField(
            model_name='competition',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='athletes.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='competition',
            name='coach_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Entrenador Encargado'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('estadal', 'Estadal'), ('liga', 'Liga'), ('copa', 'Copa'), ('viaje', 'Viaje'), ('zonal', 'Zonal'), ('nacional', 'Nacional'), ('internacional', 'Internacional')], default='liga', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sede/Ubicación'),
        ),
    ]
