# Generated by Django 5.2.12 on 2026-04-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_assistant_competition_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='set_points',
            field=models.JSONField(blank=True, default=list, verbose_name='Puntos por Set'),
        ),
    ]
