# Generated by Django 5.2.12 on 2026-04-04 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_gender'),
        ('competitions', '0003_match_set_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_competitions', to='athletes.athlete', verbose_name='Capitán'),
        ),
        migrations.AddField(
            model_name='competition',
            name='roster',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='athletes.athlete', verbose_name='Roster'),
        ),
    ]
