# Generated by Django 5.2.12 on 2026-04-04 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_athlete_gender'),
        ('competitions', '0004_competition_captain_competition_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_mvps', to='athletes.athlete', verbose_name='Atleta Relevante'),
        ),
    ]
