# Generated by Django 5.2.12 on 2026-04-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('bs', 'Bolívares (Bs)'), ('usd', 'Dólares ($)')], default='bs', max_length=5, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula/RIF'),
        ),
        migrations.AddField(
            model_name='payment',
            name='id_type',
            field=models.CharField(choices=[('V', 'Venezolano'), ('J', 'Jurídico'), ('E', 'Extranjero')], default='V', max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('pago_movil', 'Pago Móvil'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
